- name: breaking
  description: 💥 Breaking Changes
  color: #B60205

- name: bug
  description: 🐛 Bug Fixes
  color: #EB410A

- name: feature
  description: 🚀 New Features
  color: #FBCA04

- name: enhancement
  description: ✨ Improvements
  color: #59D6E6

- name: documentation
  description: 📝 Documentation Updates
  color: #6EC67B

- name: internal
  description: 🔧 Internal Changes
  color: #DB749F

- name: tests
  description: 🚦 Tests
  color: #B0B3B8

- name: dependencies
  description: 📦 Dependency Updates
  color: #0366D6

- name: skip-changelog
  desc: 🚫 Excludes a PR from the release changelog
  color: #CABA9C
