name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 💥 Breaking Changes
    label: breaking

  - title: 🚀 New Features
    label: feature

  - title: 🐛 Bug Fixes
    label: bug

  - title: ✨ Improvements
    label: enhancement

  - title: 📝 Documentation Updates
    label: documentation

  - title: 🔧 Internal Changes
    label: internal

  - title: 🚦 Tests
    label: tests

  - title: 📦 Dependency Updates
    collapse-after: 5
    label: dependencies

exclude-labels:
  - skip-changelog

version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - feature
      - dependencies
      - enhancement
  patch:
    labels:
      - bug
      - documentation
      - internal
      - tests
  default: minor

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'
template: |
  $CHANGES

  **Full Changelog:** https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
