name: 'Capistrano staging deploy'
description: 'Deploys a given branch to the staging environment with capistrano.'

inputs:
  ruby_version:
    description: The ruby version to install.
    required: true
  ssh_private_key:
    description: The SSH private key generated to access the webserver with capistrano.
    required: true
  rails_master_key:
    description: The contents of the config/master.key file in a rails app.
    required: true
  staging_credentials_key:
    description: The contents of the config/credentials/staging.key file in a rails app.
    required: true
  slack_webhook_url:
    description: The Slack webhook URL to post to.
    required: true
  slack_channel:
    description: '(Optional) The Slack channel to post to. Default value: the channel set when creating the webhook.'
  slack_username:
    description: (Optional) The username to use when posting to Slack.
    default: deploybot
  slack_icon_emoji:
    description: (Optional) An emoji to use as the picture when posting to Slack.
    default: ':rocket'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby ${{ inputs.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ inputs.ruby_version }}

    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Copy credentials master.key
      run: echo "${{ inputs.rails_master_key }}" > config/master.key
      env:
        RAILS_MASTER_KEY: ${{ inputs.rails_master_key }}
      shell: bash

    - name: Copy credentials staging.key
      run: echo "${{ inputs.staging_credentials_key }}" > config/credentials/staging.key
      env:
        STAGING_CREDENTIALS_KEY: ${{ inputs.staging_credentials_key }}
      shell: bash

    - name: Deploy to staging
      run: bundle exec cap staging deploy
      env:
        RAILS_ENV: staging
      shell: bash

    - name: Notify Slack channel
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook_url }}
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
        SLACK_USERNAME: ${{ inputs.slack_username }}
        SLACK_ICON_EMOJI: ${{ inputs.slack_icon_emoji }}
