name: 'Capistrano staging deploy'
description: 'Deploys a given branch to the staging environment with capistrano.'

inputs:
  ruby_version:
    description: The ruby version to install.
    required: true
  ssh_private_key:
    description: The SSH private key generated to access the webserver with capistrano.
    required: true
  RAILS_MASTER_KEY:
    description: The contents of the config/master.key file in a rails app.
    required: true
  STAGING_CREDENTIALS_KEY:
    description: The contents of the config/credentials/staging.key file in a rails app.
    required: true
  SLACK_WEBHOOK_URL:
    description: The Slack webhook URL to post to.
    required: true
  SLACK_CHANNEL:
    description: '(Optional) The Slack channel to post to. Default value: the channel set when creating the webhook.'
  SLACK_USERNAME:
    description: (Optional) The username to use when posting to Slack.
    default: deploybot
  SLACK_ICON_EMOJI:
    description: (Optional) An emoji to use as the picture when posting to Slack.
    default: ':rocket'

runs:
  using: 'composite'
  steps:
    - name: Setup rails dependencies
      uses: deemaze/rails_actions/setup-rails-dependencies@v2
      with:
        ruby_version: 3.2.2

    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Copy credentials master.key
      run: echo "${{ inputs.RAILS_MASTER_KEY }}" > config/master.key
      env:
        RAILS_MASTER_KEY: ${{ inputs.RAILS_MASTER_KEY }}
      shell: bash

    - name: Copy credentials staging.key
      run: echo "${{ inputs.STAGING_CREDENTIALS_KEY }}" > config/credentials/staging.key
      env:
        STAGING_CREDENTIALS_KEY: ${{ inputs.STAGING_CREDENTIALS_KEY }}
      shell: bash

    - name: Deploy to staging
      run: bundle exec cap staging deploy
      env:
        RAILS_ENV: staging
      shell: bash

    - name: Notify Slack channel
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: ${{ inputs.SLACK_CHANNEL }}
        SLACK_USERNAME: ${{ inputs.SLACK_USERNAME }}
        SLACK_ICON_EMOJI: ${{ inputs.SLACK_ICON_EMOJI }}
