name: 'Checkout and setup ruby'
description: 'This action checks out the commit, sets up Node and installs deps using yarn.'

inputs:
  ruby_version:
    required: true
  node_version:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby ${{ inputs.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ inputs.ruby_version }}

    - name: Install node ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: '${{ inputs.node_version }}'
        cache: 'yarn'

    - name: Run yarn
      run: yarn
      shell: bash
