name: 'Setup db and run rspec'
description: 'Prepares the PostgreSQL database and runs RSpec.'

inputs:
  precompile_webpacker_assets:
    description: Whether or not to precompile rails assets (usually required when using webpacker).
    required: true
    default: 'false'
  TEST_CREDENTIALS_KEY:
    description: The contents of the config/credentials/test.key file in a rails app.
    required: true

runs:
  using: 'composite'
  steps:
    # required to compile the pg gem
    - name: Install PostgreSQL client
      run: |
        sudo apt-get -yqq install libpq-dev
      shell: bash

    - name: Cache webpacker assets
      if: ${{ inputs.precompile_webpacker_assets == 'true' }}
      id: webpacker-assets
      uses: actions/cache@v3
      with:
        path: public/packs-test
        key: ${{ runner.os }}-webpacker-assets-${{ steps.extract_branch.outputs.branch }}
        restore-keys: |
          ${{ runner.os }}-webpacker-assets-

    - name: Store webpacker cache
      if: ${{ inputs.precompile_webpacker_assets == 'true' }}
      id: webpacker-cache
      uses: actions/cache@v3
      with:
        path: tmp/webpacker
        key: ${{ runner.os }}-webpacker-cache-${{ steps.extract_branch.outputs.branch }}
        restore-keys: |
          ${{ runner.os }}-webpacker-cache-

    - name: Copy credentials test.key
      run: echo "${{ inputs.TEST_CREDENTIALS_KEY }}" > config/credentials/test.key
      shell: bash

    - name: Setup db
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        bin/rails db:create
        bin/rails db:migrate
      shell: bash

    - name: Precompile assets for the test environment
      if: ${{ inputs.precompile_webpacker_assets == 'true' }}
      run: bundle exec rails assets:precompile
      shell: bash
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test

    - name: Run RSpec
      run: bundle exec rspec
      shell: bash
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
