name: 'Deploy to staging'
description: 'This action deploy the PR to staging environment'

inputs:
  ruby_version:
    required: true
  ssh_private_key:
    required: true
  rails_master_key:
    required: true
  staging_credentials_key:
    required: true
  slack_channel:
    required: false
  slack_username:
    required: false
    default: deploybot
  slack_icon_emoji:
    required: false
    default: ':rocket'
  slack_webhook_url:
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby ${{ inputs.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ inputs.ruby_version }}

    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Copy credentials master.key
      run: echo "${{ inputs.rails_master_key }}" > config/master.key
      env:
        RAILS_MASTER_KEY: ${{ inputs.rails_master_key }}
      shell: bash

    - name: Copy credentials staging.key
      run: echo "${{ inputs.staging_credentials_key }}" > config/credentials/staging.key
      env:
        STAGING_CREDENTIALS_KEY: ${{ inputs.staging_credentials_key }}
      shell: bash

    - name: Deploy to staging
      run: bundle exec cap staging deploy
      env:
        RAILS_ENV: staging
      shell: bash

    - name: Notify Slack channel
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
        SLACK_USERNAME: ${{ inputs.slack_username }}
        SLACK_ICON_EMOJI: ${{ inputs.slack_icon_emoji }}
        SLACK_WEBHOOK: ${{ inputs.slack_webhook_url }}
